"""
AI summarization - supports DeepSeek / OpenAI / any OpenAI-compatible API.
Generates elevator industry daily digests and weekly reports in Chinese and Japanese.
"""

import os
import requests


DELIMITER = "===JAPANESE==="


SYSTEM_PROMPT = f"""你是一位电梯行业的资深编辑，面向电梯企业从业者、维保人员、物业公司、监管部门和行业研究者输出每日简报。

【筛选标准】优先选择以下类型的内容，其余的直接丢弃：
- 安全事故与监管通报（电梯事故、伤亡、故障困人、市场监管局约谈/罚款）
- 政策标准发布（TSG 技术规范、GB 国标更新、总局/住建部通知）
- 老旧电梯更新改造加装（国债资金支持、惠民工程进展、典型项目案例）
- 企业重大动态（头部企业中标/签约/战略合作/新品发布/出海）
- 行业展会论坛（国际电梯展、行业技术交流会）

【丢弃标准】以下内容不要纳入：
- 纯软文、企业通稿无实质内容
- 重复或高度相似的报道（只保留最详细的一条）
- 纯地方性小新闻（仅影响单个小区的加装案例，除非有全国示范意义）

【输出要求】
你需要输出**两份**简报：先输出中文版，然后**单独一行**写 `{DELIMITER}`，再输出与中文版逐条对应、结构完全一致的日语版。
**重要：直接输出简报内容，不要加任何开场白、客套话或解释说明。第一行必须是 `## ⚠️` 分类标题或 `## 📋` 等。**

中文版格式（严格遵守）：
1. 总计 8-12 条，按类别分组：
   ## ⚠️ 安全事故与监管
   ## 📋 政策标准
   ## 🏗️ 老旧改造与加装
   ## 🏢 企业动态
   ## 📰 行业综合
2. 每条格式固定如下：
- **[标题]**：一句话说清楚发生了什么。
  - 重要性：★★★★☆ / 5
  - 核心要点：对电梯从业者/物业/监管部门的具体影响（不超过 30 字）
  - 来源：[Source Name](URL)
3. 末尾用 `### 今日观察`：3-4 句话，点出今天最值得关注的趋势或信号，有观点，不废话
4. 严格基于原文，不编造，专有名词保留品牌/型号英文，其余用中文
5. 如果某分类当天没有合适内容，直接跳过该分类，不要硬凑

日语版要求：
1. 是中文版的**忠实翻译**，条目数量、顺序、分组、重要性星级、来源链接完全一致
2. 分类标题使用对应日语：
   ## ⚠️ 安全事故と規制
   ## 📋 政策と標準
   ## 🏗️ 改修改造と増設
   ## 🏢 企業動向
   ## 📰 業界総合
3. 每条字段用日语标签：
- **[タイトル]**：一言で何が起きたか。
  - 重要度：★★★★☆ / 5
  - ポイント：業界関係者への具体的な影響（約20字以内）
  - 出典：[Source Name](URL)
4. 结尾用 `### 今日の所見`，对应中文的今日观察
5. 来源链接 URL 与中文版保持完全相同"""


WEEKLY_SYSTEM_PROMPT = """你是一位电梯行业的资深编辑，面向电梯企业从业者、维保人员、物业公司、监管部门和行业研究者输出每周简报。

【筛选标准】从一周的资讯中优先选择以下类型的内容，其余的直接丢弃：
- 安全事故与监管通报（电梯事故、伤亡、故障困人、市场监管局约谈/罚款）
- 政策标准发布（TSG 技术规范、GB 国标更新、总局/住建部通知）
- 老旧电梯更新改造加装（国债资金支持、惠民工程进展、典型项目案例）
- 企业重大动态（头部企业中标/签约/战略合作/新品发布/出海）
- 行业展会论坛（国际电梯展、行业技术交流会）

【丢弃标准】以下内容不要纳入：
- 纯软文、企业通稿无实质内容
- 同一事件的重复报道（只保留最详细的一条）
- 纯地方性小新闻（仅影响单个小区的加装案例，除非有全国示范意义）

【输出要求】
你需要输出**两份**周报：先输出中文版，然后**单独一行**写 `{DELIMITER}`，再输出与中文版逐条对应、结构完全一致的日语版。

中文版格式（严格遵守）：
1. 总计 12-18 条，按类别分组：
   ## ⚠️ 安全事故与监管
   ## 📋 政策标准
   ## 🏗️ 老旧改造与加装
   ## 🏢 企业动态
   ## 📰 行业综合
2. 每条格式固定如下：
- **[标题]**：一句话说清楚发生了什么。
  - 重要性：★★★★☆ / 5
  - 核心要点：对电梯从业者/物业/监管部门的具体影响（不超过 30 字）
  - 来源：[Source Name](URL)
  - 日期：MM-DD
3. 末尾用 `### 本周观察`：4-5 句话，总结本周最值得关注的趋势、信号和行业走向，有观点，不废话
4. 严格基于原文，不编造，专有名词保留品牌/型号英文，其余用中文
5. 如果某分类本周没有合适内容，直接跳过该分类，不要硬凑
6. 同类内容按重要性从高到低排列，相同主题的资讯可以合并为一条

日语版要求：
1. 是中文版的**忠实翻译**，条目数量、顺序、分组、重要性星级、来源链接完全一致
2. 分类标题使用对应日语：
   ## ⚠️ 安全事故と規制
   ## 📋 政策と標準
   ## 🏗️ 改修改造と増設
   ## 🏢 企業動向
   ## 📰 業界総合
3. 每条字段用日语标签：
- **[タイトル]**：一言で何が起きたか。
  - 重要度：★★★★☆ / 5
  - ポイント：業界関係者への具体的な影響（約20字以内）
  - 出典：[Source Name](URL)
  - 日付：MM-DD
4. 结尾用 `### 今週の所見`，对应中文的本周观察
5. 来源链接 URL 与中文版保持完全相同"""


def format_raw_content(data):
    """Format fetched data into a text block for the AI."""
    sections = []
    cat_labels = {
        "accident": "⚠️ 安全事故与监管",
        "regulation": "📋 政策标准",
        "renovation": "🏗️ 老旧改造与加装",
        "business": "🏢 企业动态",
        "news": "📰 行业综合",
    }

    for cat_key, cat_label in cat_labels.items():
        items = data.get(cat_key, [])
        if not items:
            continue
        sections.append(f"=== {cat_label} ===")
        for item in items:
            sections.append(
                f"[{item['source']}] {item['title']}\n"
                f"URL: {item['url']}\n"
                f"Published: {item.get('published') or 'unknown'}\n"
                f"Importance hint: {item.get('importance_hint', 3)}/5\n"
                f"{item['summary']}\n"
            )

    return "\n".join(sections)


def _wrap(text, date_str, model, title):
    return f"""# {title} - {date_str}

{text}

---
*Generated by Elevator Daily Digest using {model}*
"""


def summarize(data, date_str):
    """Generate daily digest via OpenAI-compatible API (DeepSeek by default).

    Returns (zh_markdown, ja_markdown). ja_markdown is None if the model
    didn't produce a parseable Japanese section.
    """
    api_key = os.environ.get("API_KEY")
    if not api_key:
        raise ValueError("API_KEY environment variable is required")

    base_url = os.environ.get("API_BASE_URL", "https://api.deepseek.com")
    model = os.environ.get("API_MODEL", "deepseek-chat")

    raw_content = format_raw_content(data)
    if not raw_content.strip():
        return (
            f"# 电梯行业日报 - {date_str}\n\n> 今日无内容。\n",
            None,
        )

    user_prompt = f"""今天是 {date_str}。

以下是今天收集到的电梯行业原始资讯，请整理成每日简报。
请优先选择重要性高、对行业有实际参考价值的内容：

{raw_content}"""

    url = f"{base_url}/chat/completions"
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }
    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_prompt},
        ],
        "temperature": 0.7,
        "max_tokens": 16384,
    }

    print(f"Calling {model}...")
    resp = requests.post(url, headers=headers, json=payload, timeout=180)
    resp.raise_for_status()

    result = resp.json()
    text = result["choices"][0]["message"]["content"]

    if DELIMITER in text:
        zh_text, ja_text = text.split(DELIMITER, 1)
        zh_text, ja_text = zh_text.strip(), ja_text.strip()
    else:
        print("[summarize] WARNING: no Japanese section in response; zh only.")
        zh_text, ja_text = text.strip(), None

    zh_md = _wrap(zh_text, date_str, model, "电梯行业日报")
    ja_md = _wrap(ja_text, date_str, model, "エレベーター業界デイリーダイジェスト") if ja_text else None
    return zh_md, ja_md


def summarize_weekly(data, week_label):
    """Generate weekly digest via OpenAI-compatible API.

    Returns (zh_markdown, ja_markdown).
    """
    api_key = os.environ.get("API_KEY")
    if not api_key:
        raise ValueError("API_KEY environment variable is required")

    base_url = os.environ.get("API_BASE_URL", "https://api.deepseek.com")
    model = os.environ.get("API_MODEL", "deepseek-chat")

    raw_content = format_raw_content(data)
    if not raw_content.strip():
        return f"# 电梯行业周报 - {week_label}\n\n> 本周无内容。\n", None

    user_prompt = f"""本周为 {week_label}。

以下是本周收集到的电梯行业原始资讯，请整理成每周简报。
请优先选择重要性高、对行业有实际参考价值的内容：

{raw_content}"""

    url = f"{base_url}/chat/completions"
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }
    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": WEEKLY_SYSTEM_PROMPT},
            {"role": "user", "content": user_prompt},
        ],
        "temperature": 0.7,
        "max_tokens": 16384,
    }

    print(f"Calling {model} for weekly digest...")
    resp = requests.post(url, headers=headers, json=payload, timeout=180)
    resp.raise_for_status()

    result = resp.json()
    text = result["choices"][0]["message"]["content"]

    if DELIMITER in text:
        zh_text, ja_text = text.split(DELIMITER, 1)
        zh_text, ja_text = zh_text.strip(), ja_text.strip()
    else:
        print("[summarize_weekly] WARNING: no Japanese section in response; zh only.")
        zh_text, ja_text = text.strip(), None

    zh_md = _wrap(zh_text, week_label, model, "电梯行业周报")
    ja_md = _wrap(ja_text, week_label, model, "エレベーター業界週報") if ja_text else None
    return zh_md, ja_md
