"""
AI summarization - supports DeepSeek / OpenAI / any OpenAI-compatible API.
Generates elevator industry daily digests and weekly reports in Chinese and Japanese.
"""

import os
import re
import requests


SYSTEM_PROMPT = """你是一位电梯行业的资深编辑，面向电梯企业从业者、维保人员、物业公司、监管部门和行业研究者输出每日简报。

【筛选标准】优先选择以下类型的内容，其余的直接丢弃：
- 政策标准发布（TSG 技术规范、GB 国标更新、总局/住建部通知）
- 老旧电梯更新改造加装（国债资金支持、惠民工程进展、典型项目案例）
- 企业重大动态（头部企业中标/签约/战略合作/新品发布/出海）
- 行业展会论坛（国际电梯展、行业技术交流会）

【丢弃标准】以下内容不要纳入：
- 纯软文、企业通稿无实质内容
- 重复或高度相似的报道（只保留最详细的一条）
- 纯地方性小新闻（仅影响单个小区的加装案例，除非有全国示范意义）

【输出要求】
直接输出简报正文，不要加任何开场白、客套话或解释说明。

格式（严格遵守）：
1. 总计 6-10 条，按类别分组：
   ## 📋 政策标准
   ## 🏗️ 老旧改造与加装
   ## 🏢 企业动态
   ## 📰 行业综合
2. 每条格式固定如下（示例）：
- **山东淄博电梯安装坍塌事故调查报告公布 1死2伤**
  - AI摘要：不看原文就能了解新闻全貌。写清楚谁、在哪、什么时候、发生了什么、涉及什么数据或金额、意味着什么。不少于300字
  - 来源：[新电梯网](https://www.xindianti.cn/news/show-50747.html)
  - 日期：07-09
3. 末尾用 `### 今日观察`：3-4 句话，点出今天最值得关注的趋势或信号，有观点，不废话
4. 严格基于原文，不编造，专有名词保留品牌/型号英文，其余用中文
5. 如果某分类当天没有合适内容，直接跳过该分类，不要硬凑
6. 标题只用 **加粗标题**，不要加冒号简述（详情由AI摘要承载），不要在标题前加分类标签如 [事故通报] 等"""



WEEKLY_SYSTEM_PROMPT = """你是一位电梯行业的资深编辑，面向电梯企业从业者、维保人员、物业公司、监管部门和行业研究者输出每周简报。

【筛选标准】从一周的资讯中优先选择以下类型的内容，其余的直接丢弃：
- 政策标准发布（TSG 技术规范、GB 国标更新、总局/住建部通知）
- 老旧电梯更新改造加装（国债资金支持、惠民工程进展、典型项目案例）
- 企业重大动态（头部企业中标/签约/战略合作/新品发布/出海）
- 行业展会论坛（国际电梯展、行业技术交流会）

【丢弃标准】以下内容不要纳入：
- 纯软文、企业通稿无实质内容
- 同一事件的重复报道（只保留最详细的一条）
- 纯地方性小新闻（仅影响单个小区的加装案例，除非有全国示范意义）

【输出要求】
直接输出周报正文，不要加任何开场白、客套话或解释说明。

格式（严格遵守）：
1. 总计 8-14 条，按类别分组：
   ## 📋 政策标准
   ## 🏗️ 老旧改造与加装
   ## 🏢 企业动态
   ## 📰 行业综合
2. 每条格式固定如下（示例）：
- **山东淄博电梯安装坍塌事故调查报告公布 1死2伤**
  - AI摘要：不看原文就能了解新闻全貌。写清楚谁、在哪、什么时候、发生了什么、涉及什么数据或金额、意味着什么。不少于300字
  - 来源：[新电梯网](https://www.xindianti.cn/news/show-50747.html)
  - 日期：07-09
3. 末尾用 `### 本周观察`：4-5 句话，总结本周最值得关注的趋势、信号和行业走向，有观点，不废话
4. 严格基于原文，不编造，专有名词保留品牌/型号英文，其余用中文
5. 如果某分类本周没有合适内容，直接跳过该分类，不要硬凑
6. 同类内容按日期从新到旧排列，相同主题的资讯可以合并为一条
7. 标题只用 **加粗标题**，不要加冒号简述（详情由AI摘要承载），不要在标题前加分类标签如 [事故通报] 等
"""


TRANSLATE_SYSTEM_PROMPT = """你是一个专业的中日翻译专家，擅长将电梯行业的中文简报翻译成自然流畅的日语。

要求：
1. 忠实翻译，不增不减，保持原有结构、格式、Markdown 标记、链接完全不变
2. 分类标题翻译为日语（## ⚠️ 安全事故与监管 → ## ⚠️ 安全事故と規制 等）
3. 字段标签翻译为日语（AI摘要 → AI要約，来源 → 出典，日期 → 日付 等）
4. 观察标题翻译（今日观察 → 今日の所見，本周观察 → 今週の所見）
5. 专有名词（公司名、品牌名、地名）保留原文不变
6. 直接输出翻译结果，不要加任何开场白或解释
"""


_CAT_TRANSLATION = {
    "安全事故与监管": "安全事故と規制",
    "政策标准": "政策と標準",
    "老旧改造与加装": "改修改造と増設",
    "企业动态": "企業動向",
    "行业综合": "業界総合",
}

_LABEL_TRANSLATION = {
    "AI摘要：": "AI要約：",
    "来源：": "出典：",
    "日期：": "日付：",
    "今日观察": "今日の所見",
    "本周观察": "今週の所見",
}


def format_raw_content(data):
    """Format fetched data into a text block for the AI."""
    sections = []
    cat_labels = {
        "accident": "⚠️ 安全事故与监管",
        "regulation": "📋 政策标准",
        "renovation": "🏗️ 老旧改造与加装",
        "business": "🏢 企业动态",
        "news": "📰 行业综合",
    }

    for cat_key, cat_label in cat_labels.items():
        items = data.get(cat_key, [])
        if not items:
            continue
        sections.append(f"=== {cat_label} ===")
        for item in items:
            sections.append(
                f"[{item['source']}] {item['title']}\n"
                f"URL: {item['url']}\n"
                f"Published: {item.get('published') or 'unknown'}\n"
                f"Importance hint: {item.get('importance_hint', 3)}/5\n"
                f"{item['summary']}\n"
            )

    return "\n".join(sections)


def _wrap(text, date_str, model, title):
    # Strip any AI-generated title/h1 lines to avoid duplication
    text = re.sub(r'^#\s+[^\n]+\n+', '', text.strip())
    return f"""# {title} - {date_str}

{text}

---
*Generated by Elevator Daily Digest using {model}*
"""


def _call_api(system_prompt, user_prompt, max_tokens=8192):
    """Make a single API call, return text content."""
    api_key = os.environ.get("API_KEY")
    if not api_key:
        raise ValueError("API_KEY environment variable is required")

    base_url = os.environ.get("API_BASE_URL", "https://api.deepseek.com")
    model = os.environ.get("API_MODEL", "deepseek-chat")

    url = f"{base_url}/chat/completions"
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }
    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
        "temperature": 0.9,
        "max_tokens": max_tokens,
    }

    resp = requests.post(url, headers=headers, json=payload, timeout=180)
    resp.raise_for_status()
    return resp.json()["choices"][0]["message"]["content"]


def _translate_to_japanese(zh_text):
    """Translate Chinese digest to Japanese via a separate API call."""
    model = os.environ.get("API_MODEL", "deepseek-chat")
    print(f"  Translating to Japanese ({model})...")

    user_prompt = f"""请将以下中文电梯行业简报逐句翻译成日语：

{zh_text}"""

    ja_text = _call_api(TRANSLATE_SYSTEM_PROMPT, user_prompt, max_tokens=8192)
    return ja_text.strip()


def summarize(data, date_str):
    """Generate daily digest (zh), then translate to ja."""
    model = os.environ.get("API_MODEL", "deepseek-chat")

    raw_content = format_raw_content(data)
    if not raw_content.strip():
        return (f"# 电梯行业日报 - {date_str}\n\n> 今日无内容。\n", None)

    user_prompt = f"""今天是 {date_str}。

以下是今天收集到的电梯行业原始资讯，请整理成每日简报。
请优先选择重要性高、对行业有实际参考价值的内容：

{raw_content}"""

    print(f"Calling {model}...")
    zh_text = _call_api(SYSTEM_PROMPT, user_prompt, max_tokens=16384)
    zh_text = zh_text.strip()

    zh_md = _wrap(zh_text, date_str, model, "电梯行业日报")

    # Translate to Japanese
    try:
        ja_text = _translate_to_japanese(zh_text)
        ja_md = _wrap(ja_text, date_str, model, "エレベーター業界デイリーダイジェスト")
    except Exception as e:
        print(f"  Japanese translation failed: {e}")
        ja_md = None

    return zh_md, ja_md


def summarize_weekly(data, week_label):
    """Generate weekly digest (zh), then translate to ja."""
    model = os.environ.get("API_MODEL", "deepseek-chat")

    raw_content = format_raw_content(data)
    if not raw_content.strip():
        return f"# 电梯行业周报 - {week_label}\n\n> 本周无内容。\n", None

    user_prompt = f"""本周为 {week_label}。

以下是本周收集到的电梯行业原始资讯，请整理成每周简报。
请优先选择重要性高、对行业有实际参考价值的内容：

{raw_content}"""

    print(f"Calling {model} for weekly digest...")
    zh_text = _call_api(WEEKLY_SYSTEM_PROMPT, user_prompt, max_tokens=16384)
    zh_text = zh_text.strip()

    zh_md = _wrap(zh_text, week_label, model, "电梯行业周报")

    # Translate to Japanese
    try:
        ja_text = _translate_to_japanese(zh_text)
        ja_md = _wrap(ja_text, week_label, model, "エレベーター業界週報")
    except Exception as e:
        print(f"  Japanese translation failed: {e}")
        ja_md = None

    return zh_md, ja_md
